<a href="https://colab.research.google.com/github/yahuy1/CSE432/blob/main/HW5_Coding_nguyenhg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1:

In [18]:
import numpy as np

def backpropagation1(w1, x1, w2, x2):
  # Use np.around to prevent trigonometry functions from not reaching 0

  # Forward
  f1_1 = w1 * x1
  f1_2 = np.around(np.sin(f1_1), decimals = 10)
  f1_3 = f1_2**2
  f2_1 = w2 * x2
  f2_2 = np.around(np.cos(f2_1), decimals = 10)
  f3 = f1_3 + f2_2
  f4 = f3 + 2
  f5 = 1 / f4

  # Backward
  b5 = 1
  b4 = (-1 / (f4**2)) * b5
  b3 = 1 * b4
  b1_3 = 1 * b3
  b1_2 = 2 * f1_2 * b1_3
  b1_1 = np.around(np.cos(f1_1) * b1_2, decimals = 10)
  b2_2 = 1 * b3
  b2_1 = np.around(-np.sin(f2_1) * b2_2, decimals = 10)

  # Result with respect to each parameter
  partial_w1 = x1 * b1_1
  partial_x1 = w1 * b1_1
  partial_w2 = x2 * b2_1
  partial_x2 = w2 * b2_1

  return partial_w1, partial_x1, partial_w2, partial_x2

print("Result with respect to w1, x1, w2, x2 respectively:")
backpropagation1(np.pi / 2, 1, np.pi / 2, 2)


Result with respect to w1, x1, w2, x2 respectively:


(-0.0, -0.0, 0.0, 0.0)

Problem 2:

In [25]:
import numpy as np

def backpropagation2(W, x):
  # Forward
  f = np.dot(W, x)

  # Backward
  b = 1

  # Result with respect to each parameter
  partial_W = b * np.transpose(x)
  partial_x = np.transpose(W) * b

  return partial_W, partial_x

W_input = [[2, 1, 2],
           [1, 3, 1],
           [7, 4, 7]]
x_input = [[-1],
           [0],
           [1]]

W_result, x_result = backpropagation2(W_input, x_input)
print("Result for W:", W_result,"\n")
print("Result for x:\n", x_result)

Result for W: [[-1  0  1]] 

Result for x:
 [[2 1 7]
 [1 3 4]
 [2 1 7]]
